import { Tool } from "@/types/tools";

export const tools: Tool[] = [
  // ── Formatters & Validators ────────────────────────────────
  {
    name: "JSON Formatter",
    description: "Format, validate, and minify JSON with syntax highlighting.",
    path: "/json-formatter",
    icon: "Braces",
    category: "Formatters & Validators",
    tags: ["json", "format", "validate", "minify"],
  },
  {
    name: "XML Formatter",
    description: "Prettify and validate XML documents instantly.",
    path: "/xml-formatter",
    icon: "Code2",
    category: "Formatters & Validators",
    tags: ["xml", "format", "validate"],
  },
  {
    name: "SQL Formatter",
    description: "Format and beautify SQL queries for better readability.",
    path: "/sql-formatter",
    icon: "Database",
    category: "Formatters & Validators",
    tags: ["sql", "format", "query", "database"],
  },
  {
    name: "CSS Formatter",
    description: "Prettify and minify CSS stylesheets.",
    path: "/css-formatter",
    icon: "Paintbrush",
    category: "Formatters & Validators",
    tags: ["css", "format", "minify", "style"],
  },
  {
    name: "Markdown Preview",
    description: "Write Markdown and see a live rendered HTML preview.",
    path: "/markdown-preview",
    icon: "BookOpen",
    category: "Formatters & Validators",
    tags: ["markdown", "preview", "html", "readme"],
  },

  // ── Encoders & Decoders ────────────────────────────────────
  {
    name: "Base64 Encoder / Decoder",
    description: "Encode or decode Base64 strings and files.",
    path: "/base64",
    icon: "Binary",
    category: "Encoders & Decoders",
    tags: ["base64", "encode", "decode"],
  },
  {
    name: "URL Encoder / Decoder",
    description: "Encode or decode URL components and query strings.",
    path: "/url-encoder",
    icon: "Link",
    category: "Encoders & Decoders",
    tags: ["url", "encode", "decode", "uri"],
  },
  {
    name: "JWT Decoder",
    description: "Decode and inspect JWT tokens — header, payload, and signature.",
    path: "/jwt-decoder",
    icon: "KeyRound",
    category: "Encoders & Decoders",
    tags: ["jwt", "token", "decode", "auth"],
  },
  {
    name: "JWT Generator",
    description: "Generate signed JWT tokens with custom payload and secret.",
    path: "/jwt-generator",
    icon: "KeySquare",
    category: "Encoders & Decoders",
    tags: ["jwt", "token", "generate", "hmac", "auth"],
  },
  {
    name: "HTML Entity Encoder",
    description: "Encode special characters to HTML entities and decode them back.",
    path: "/html-entity",
    icon: "FileCode",
    category: "Encoders & Decoders",
    tags: ["html", "entity", "encode", "decode", "escape"],
  },
  {
    name: "String Escape / Unescape",
    description: "Escape or unescape JSON, JavaScript, and SQL strings.",
    path: "/string-escape",
    icon: "Terminal",
    category: "Encoders & Decoders",
    tags: ["string", "escape", "unescape", "json", "javascript"],
  },

  // ── Converters ─────────────────────────────────────────────
  {
    name: "JSON ↔ YAML",
    description: "Convert between JSON and YAML formats instantly.",
    path: "/json-yaml",
    icon: "ArrowLeftRight",
    category: "Converters",
    tags: ["json", "yaml", "convert"],
  },
  {
    name: "CSV ↔ JSON",
    description: "Convert CSV data to JSON and back with header support.",
    path: "/csv-json",
    icon: "Table2",
    category: "Converters",
    tags: ["csv", "json", "convert", "data"],
  },
  {
    name: "JSON → TypeScript",
    description: "Generate TypeScript interfaces and types from a JSON object.",
    path: "/json-to-ts",
    icon: "FileType",
    category: "Converters",
    tags: ["json", "typescript", "interface", "types", "generate"],
  },
  {
    name: "Color Converter",
    description: "Convert colors between HEX, RGB, HSL, and CSS names.",
    path: "/color-converter",
    icon: "Palette",
    category: "Converters",
    tags: ["color", "hex", "rgb", "hsl", "convert"],
  },
  {
    name: "Number Base Converter",
    description: "Convert numbers between Binary, Octal, Decimal, and Hexadecimal.",
    path: "/number-base",
    icon: "Hash",
    category: "Converters",
    tags: ["binary", "octal", "decimal", "hex", "base", "convert"],
  },
  {
    name: "Timestamp Converter",
    description: "Convert Unix timestamps to human-readable dates and vice versa.",
    path: "/timestamp",
    icon: "Clock",
    category: "Converters",
    tags: ["timestamp", "unix", "epoch", "date", "convert"],
  },

  {
    name: "HTML Formatter",
    description: "Prettify and minify HTML markup. All processing in your browser.",
    path: "/html-formatter",
    icon: "Globe",
    category: "Formatters & Validators",
    tags: ["html", "format", "minify", "beautify"],
  },
  {
    name: "JSON Schema Generator",
    description: "Generate a JSON Schema from any JSON object automatically.",
    path: "/json-schema",
    icon: "Layers",
    category: "Formatters & Validators",
    tags: ["json", "schema", "generate", "validate"],
  },

  // ── Generators ─────────────────────────────────────────────
  {
    name: "Hash Generator",
    description: "Generate MD5, SHA-1, SHA-256, and SHA-512 hashes from any text.",
    path: "/hash-generator",
    icon: "ShieldCheck",
    category: "Generators",
    tags: ["hash", "md5", "sha256", "sha512", "crypto"],
  },
  {
    name: "UUID Generator",
    description: "Generate RFC-compliant UUIDs (v4 and v7) in bulk.",
    path: "/uuid-generator",
    icon: "Fingerprint",
    category: "Generators",
    tags: ["uuid", "guid", "random", "generate"],
  },
  {
    name: "Password Generator",
    description: "Generate strong, customizable passwords with entropy score.",
    path: "/password-generator",
    icon: "Lock",
    category: "Generators",
    tags: ["password", "generate", "security", "random"],
  },
  {
    name: "Lorem Ipsum Generator",
    description: "Generate placeholder Lorem Ipsum text by words, sentences, or paragraphs.",
    path: "/lorem-ipsum",
    icon: "AlignLeft",
    category: "Generators",
    tags: ["lorem", "ipsum", "placeholder", "text"],
  },
  {
    name: "QR Code Generator",
    description: "Generate QR codes from any text or URL and download as PNG.",
    path: "/qr-code",
    icon: "QrCode",
    category: "Generators",
    tags: ["qr", "qrcode", "generate", "url"],
  },
  {
    name: "Fake Data Generator",
    description: "Generate realistic fake names, emails, addresses, and more for testing.",
    path: "/fake-data",
    icon: "UserRound",
    category: "Generators",
    tags: ["fake", "data", "mock", "test", "generate"],
  },
  {
    name: "CSS Gradient Generator",
    description: "Build linear and radial CSS gradients visually and copy the code.",
    path: "/css-gradient",
    icon: "Wand2",
    category: "Generators",
    tags: ["css", "gradient", "linear", "radial", "background"],
  },
  {
    name: "CSS Box Shadow Generator",
    description: "Create and preview CSS box shadows visually with live code output.",
    path: "/css-box-shadow",
    icon: "Frame",
    category: "Generators",
    tags: ["css", "box-shadow", "shadow", "design"],
  },
  {
    name: "Color Palette Generator",
    description: "Generate harmonious color palettes from a base color.",
    path: "/color-palette",
    icon: "PaintBucket",
    category: "Generators",
    tags: ["color", "palette", "design", "complementary", "harmony"],
  },
  {
    name: "UTM Builder",
    description: "Build UTM-tagged URLs for tracking marketing campaigns.",
    path: "/utm-builder",
    icon: "Share2",
    category: "Generators",
    tags: ["utm", "url", "tracking", "analytics", "marketing"],
  },
  {
    name: "Slug Generator",
    description: "Convert any text into a URL-safe slug for use in paths and IDs.",
    path: "/slug-generator",
    icon: "Link2",
    category: "Generators",
    tags: ["slug", "url", "kebab", "sanitize", "permalink"],
  },
  {
    name: "Markdown Table Generator",
    description: "Build Markdown tables visually and copy the formatted output.",
    path: "/markdown-table",
    icon: "TableProperties",
    category: "Generators",
    tags: ["markdown", "table", "generate", "grid"],
  },
  {
    name: "Meta Tag Generator",
    description: "Generate SEO and Open Graph meta tags for HTML <head>.",
    path: "/meta-tag",
    icon: "Tags",
    category: "Generators",
    tags: ["meta", "seo", "og", "opengraph", "html", "head"],
  },

  // ── Converters (additional) ────────────────────────────────
  {
    name: "YAML Validator",
    description: "Validate and format YAML files with clear error messages.",
    path: "/yaml-validator",
    icon: "FileCheck2",
    category: "Formatters & Validators",
    tags: ["yaml", "validate", "format", "lint"],
  },
  {
    name: "XML → JSON",
    description: "Convert XML documents to JSON format instantly.",
    path: "/xml-json",
    icon: "FileJson2",
    category: "Converters",
    tags: ["xml", "json", "convert", "transform"],
  },
  {
    name: "Date Calculator",
    description: "Calculate age, days between dates, and add/subtract durations.",
    path: "/date-calculator",
    icon: "CalendarDays",
    category: "Converters",
    tags: ["date", "age", "duration", "days", "calculate"],
  },
  {
    name: "Unit Converter",
    description: "Convert length, weight, temperature, and more between common units.",
    path: "/unit-converter",
    icon: "Ruler",
    category: "Converters",
    tags: ["unit", "convert", "length", "weight", "temperature"],
  },
  {
    name: "URL Parser",
    description: "Break any URL into its components: protocol, host, path, query params, and hash.",
    path: "/url-parser",
    icon: "Unlink",
    category: "Converters",
    tags: ["url", "parse", "query", "params", "uri"],
  },
  {
    name: "Markdown → HTML",
    description: "Convert a Markdown table or document to clean HTML markup.",
    path: "/markdown-html",
    icon: "FileSpreadsheet",
    category: "Converters",
    tags: ["markdown", "html", "table", "convert"],
  },
  {
    name: "Image → Base64",
    description: "Encode images to Base64 data URLs for embedding in HTML and CSS.",
    path: "/image-base64",
    icon: "ImageIcon",
    category: "Converters",
    tags: ["image", "base64", "encode", "data-url", "embed"],
  },
  {
    name: "Text ↔ Binary",
    description: "Convert text to binary (0s and 1s) and back.",
    path: "/text-binary",
    icon: "Cpu",
    category: "Converters",
    tags: ["text", "binary", "bits", "convert", "encode"],
  },
  {
    name: "Aspect Ratio Calculator",
    description: "Calculate and scale aspect ratios for images and video.",
    path: "/aspect-ratio",
    icon: "Maximize2",
    category: "Converters",
    tags: ["aspect", "ratio", "resolution", "scale", "video", "image"],
  },

  // ── Testers & Analysis ─────────────────────────────────────
  {
    name: "Regex Tester",
    description: "Test regular expressions with live match highlighting.",
    path: "/regex-tester",
    icon: "Regex",
    category: "Testers & Analysis",
    tags: ["regex", "regexp", "test", "pattern"],
  },
  {
    name: "CRON Expression Tester",
    description: "Validate CRON expressions and preview the next scheduled run times.",
    path: "/cron-tester",
    icon: "CalendarClock",
    category: "Testers & Analysis",
    tags: ["cron", "schedule", "interval", "jobs"],
  },
  {
    name: "Text Diff Viewer",
    description: "Compare two text blocks side by side and highlight differences.",
    path: "/diff-viewer",
    icon: "Columns2",
    category: "Testers & Analysis",
    tags: ["diff", "compare", "text", "changes"],
  },
  {
    name: "Word & Character Counter",
    description: "Count words, characters, lines, sentences, and estimate reading time.",
    path: "/word-counter",
    icon: "FileText",
    category: "Testers & Analysis",
    tags: ["word", "character", "count", "readability"],
  },
  {
    name: "Text Case Converter",
    description: "Convert text between camelCase, snake_case, PascalCase, kebab-case, and more.",
    path: "/text-case",
    icon: "CaseSensitive",
    category: "Testers & Analysis",
    tags: ["case", "camel", "snake", "pascal", "kebab", "convert"],
  },
  {
    name: "Byte Size Calculator",
    description: "Calculate the UTF-8 byte size of any string or payload.",
    path: "/byte-size",
    icon: "HardDrive",
    category: "Testers & Analysis",
    tags: ["byte", "size", "utf8", "encoding", "payload"],
  },
  {
    name: "HTTP Status Reference",
    description: "Quick reference for all HTTP status codes with descriptions.",
    path: "/http-status",
    icon: "Globe",
    category: "Testers & Analysis",
    tags: ["http", "status", "code", "reference", "rest"],
  },
  {
    name: "User-Agent Parser",
    description: "Parse and decode browser and device User-Agent strings.",
    path: "/useragent-parser",
    icon: "Monitor",
    category: "Testers & Analysis",
    tags: ["useragent", "browser", "device", "parse"],
  },
  {
    name: "JSON Path Tester",
    description: "Test JSONPath expressions against JSON data and inspect results.",
    path: "/jsonpath",
    icon: "Search",
    category: "Testers & Analysis",
    tags: ["jsonpath", "json", "query", "test", "extract"],
  },
  {
    name: "IP Subnet Calculator",
    description: "Calculate network address, broadcast, host range, and CIDR notation.",
    path: "/ip-subnet",
    icon: "Network",
    category: "Testers & Analysis",
    tags: ["ip", "subnet", "cidr", "network", "ipv4"],
  },
  {
    name: "Chmod Calculator",
    description: "Convert Unix file permissions between symbolic and numeric modes.",
    path: "/chmod",
    icon: "Shield",
    category: "Testers & Analysis",
    tags: ["chmod", "permissions", "unix", "linux", "octal"],
  },
  {
    name: "Semver Analyzer",
    description: "Parse, compare, and validate Semantic Versioning strings.",
    path: "/semver",
    icon: "Tag",
    category: "Testers & Analysis",
    tags: ["semver", "version", "semantic", "compare", "parse"],
  },
  {
    name: "Line Sorter",
    description: "Sort, deduplicate, and shuffle lines of text.",
    path: "/line-sorter",
    icon: "ArrowUpDown",
    category: "Testers & Analysis",
    tags: ["sort", "lines", "deduplicate", "text", "organize"],
  },
  {
    name: "Find & Replace",
    description: "Find and replace text with plain text or regex patterns.",
    path: "/find-replace",
    icon: "Replace",
    category: "Testers & Analysis",
    tags: ["find", "replace", "regex", "text", "substitute"],
  },
  {
    name: "Percentage Calculator",
    description: "Calculate percentages, discounts, increases, and decreases.",
    path: "/percentage",
    icon: "Percent",
    category: "Testers & Analysis",
    tags: ["percentage", "percent", "discount", "calculate", "math"],
  },
  {
    name: "CSV Viewer",
    description: "Upload and preview CSV files as an interactive table.",
    path: "/csv-viewer",
    icon: "Table",
    category: "Testers & Analysis",
    tags: ["csv", "table", "view", "data", "spreadsheet"],
  },
  {
    name: "JSON Diff",
    description: "Compare two JSON objects and highlight added, removed, and changed keys.",
    path: "/json-diff",
    icon: "GitCompare",
    category: "Testers & Analysis",
    tags: ["json", "diff", "compare", "changes"],
  },
  {
    name: "Password Strength Checker",
    description: "Analyze password strength, entropy, and estimated crack time.",
    path: "/password-strength",
    icon: "ShieldAlert",
    category: "Testers & Analysis",
    tags: ["password", "strength", "security", "entropy"],
  },
  {
    name: "Readability Score",
    description: "Analyze text readability with Flesch-Kincaid and other scores.",
    path: "/readability",
    icon: "GraduationCap",
    category: "Testers & Analysis",
    tags: ["readability", "flesch", "kincaid", "text", "score"],
  },
  {
    name: "ASCII Table",
    description: "Full ASCII and extended character reference table with hex, decimal, and binary.",
    path: "/ascii-table",
    icon: "Grid3x3",
    category: "Testers & Analysis",
    tags: ["ascii", "character", "table", "reference", "unicode"],
  },
  {
    name: "Color Contrast Checker",
    description: "Check foreground/background color contrast ratios against WCAG AA and AAA.",
    path: "/color-contrast",
    icon: "Eye",
    category: "Testers & Analysis",
    tags: ["color", "contrast", "wcag", "accessibility", "a11y"],
  },
  {
    name: "Number Formatter",
    description: "Format numbers with locale, currency, decimals, and thousands separators.",
    path: "/number-formatter",
    icon: "Calculator",
    category: "Testers & Analysis",
    tags: ["number", "format", "currency", "locale", "decimal"],
  },

  // ── New tools ──────────────────────────────────────────────
  {
    name: "HTML → Markdown",
    description: "Convert HTML markup to clean, readable Markdown text.",
    path: "/html-to-markdown",
    icon: "FileCode",
    category: "Converters",
    tags: ["html", "markdown", "convert"],
  },
  {
    name: "TOML ↔ JSON",
    description: "Convert between TOML and JSON configuration formats.",
    path: "/toml-json",
    icon: "ArrowLeftRight",
    category: "Converters",
    tags: ["toml", "json", "convert", "config"],
  },
  {
    name: "JSON Schema Validator",
    description: "Validate JSON data against a JSON Schema (Draft-07).",
    path: "/json-schema-validator",
    icon: "FileCheck2",
    category: "Formatters & Validators",
    tags: ["json", "schema", "validate", "ajv"],
  },
  {
    name: "Timezone Converter",
    description: "Convert a date and time between any two IANA timezones.",
    path: "/timezone-converter",
    icon: "CalendarClock",
    category: "Converters",
    tags: ["timezone", "convert", "time", "date", "iana"],
  },
  {
    name: "HTML to JSX",
    description: "Convert HTML markup to React JSX — renames attributes, self-closes void elements, converts styles.",
    path: "/html-to-jsx",
    icon: "Code2",
    category: "Converters",
    tags: ["html", "jsx", "react", "convert", "className"],
  },
  {
    name: "cURL to Code",
    description: "Convert a cURL command to JavaScript fetch, Axios, Python requests, or Go.",
    path: "/curl-to-code",
    icon: "Terminal",
    category: "Converters",
    tags: ["curl", "fetch", "convert", "http", "python", "axios"],
  },
  {
    name: "CSS Flexbox Playground",
    description: "Build CSS flexbox layouts visually and copy the generated CSS.",
    path: "/css-flexbox",
    icon: "Columns2",
    category: "Generators",
    tags: ["css", "flexbox", "layout", "playground", "generate"],
  },
  {
    name: "Color Picker",
    description: "Pick colors visually using HSL/RGB sliders and copy in HEX, RGB, or HSL format.",
    path: "/color-picker",
    icon: "Paintbrush",
    category: "Generators",
    tags: ["color", "picker", "hex", "rgb", "hsl", "visual"],
  },
  {
    name: "ENV File Parser",
    description: "Parse .env files — extract key/value pairs, detect syntax errors, and export as JSON.",
    path: "/env-parser",
    icon: "FileText",
    category: "Testers & Analysis",
    tags: ["env", "dotenv", "config", "parse", "environment"],
  },
  {
    name: "JavaScript Minifier",
    description: "Minify JavaScript code by removing comments and collapsing whitespace.",
    path: "/js-minifier",
    icon: "Wand2",
    category: "Formatters & Validators",
    tags: ["javascript", "minify", "compress", "js"],
  },
  {
    name: "CSS Specificity Calculator",
    description: "Calculate the specificity score (IDs, classes, elements) for any CSS selector.",
    path: "/css-specificity",
    icon: "Tag",
    category: "Testers & Analysis",
    tags: ["css", "specificity", "selector", "ids", "classes"],
  },
  {
    name: "Base32 Encoder / Decoder",
    description: "Encode text to Base32 (RFC 4648) or decode Base32 back to text.",
    path: "/base32",
    icon: "Binary",
    category: "Encoders & Decoders",
    tags: ["base32", "encode", "decode", "rfc4648"],
  },
  {
    name: "HMAC Generator",
    description: "Generate HMAC message authentication codes using SHA-256, SHA-1, or SHA-512.",
    path: "/hmac-generator",
    icon: "Fingerprint",
    category: "Generators",
    tags: ["hmac", "hash", "signature", "crypto", "sha256"],
  },
  {
    name: "Text Repeater",
    description: "Repeat any text N times with a custom separator.",
    path: "/text-repeater",
    icon: "AlignLeft",
    category: "Testers & Analysis",
    tags: ["text", "repeat", "duplicate", "string"],
  },
  {
    name: "Morse Code",
    description: "Encode text to Morse code (dots and dashes) or decode Morse code back to text.",
    path: "/morse-code",
    icon: "Hash",
    category: "Encoders & Decoders",
    tags: ["morse", "encode", "decode", "dots", "dashes"],
  },
  {
    name: "TOTP Generator",
    description: "Generate Time-based One-Time Passwords (RFC 6238) — compatible with Google Authenticator.",
    path: "/totp-generator",
    icon: "Lock",
    category: "Generators",
    tags: ["totp", "otp", "2fa", "authenticator", "mfa"],
  },
  {
    name: "Open Graph Preview",
    description: "Preview how your page looks when shared on Twitter/X, LinkedIn, and Facebook.",
    path: "/og-preview",
    icon: "Eye",
    category: "Testers & Analysis",
    tags: ["og", "opengraph", "social", "preview", "seo", "twitter"],
  },
  {
    name: "SVG Minifier",
    description: "Remove comments, metadata, and whitespace from SVG files to reduce file size.",
    path: "/svg-minifier",
    icon: "ImageIcon",
    category: "Formatters & Validators",
    tags: ["svg", "minify", "optimize", "compress"],
  },
  {
    name: "XML ↔ YAML",
    description: "Convert between XML and YAML formats.",
    path: "/xml-yaml",
    icon: "ArrowLeftRight",
    category: "Converters",
    tags: ["xml", "yaml", "convert", "transform"],
  },
];

export const categories = [
  "Formatters & Validators",
  "Encoders & Decoders",
  "Converters",
  "Generators",
  "Testers & Analysis",
] as const;

export function getToolsByCategory(category: string) {
  return tools.filter((t) => t.category === category);
}
